version: '3'
services:
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    networks:
      - space-travels

  hyperspace:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    networks:
      - space-travels

networks:
  space-travels:
